### ISSUE TITLE
zap2it URLS no longer work

### ISSUE THREAD

**Issue by bcacbe** [learningit/script.USChannels#1]
zap2it URLS no longer work

For example: 

http://www.zap2it.com/tvgrid/_xhr/schedule?time=&lineupid=USA-DITV542-DEFAULT&zip=45342&tz=US%2FEastern&count=50&searchid=&tz=US%2FEastern

returns an error

Is there a new URL format?

**Comment by learningit** [comment]
This will not be fixed anytime soon, if ever.
